CREATE TABLE IF  NOT EXISTS OrderTranportDetail(
OTDId INT AUTO_INCREMENT NOT NULL,
OrderId INT NOT NULL,
SourceLocation NVARCHAR(200),
DestinationLocation NVARCHAR(200),
TransportMode NVARCHAR(50),
VehicleNumber NVARCHAR(200),
TransporterAddress NVARCHAR(1000),
MobileNumber NVARCHAR(10),
OTDCrd DATETIME,
OTDCrdBy NVARCHAR(200),
OTDUpd	DATETIME,
OTDUpdBy	NVARCHAR(200),
CONSTRAINT PK_OrderTranportDetail PRIMARY KEY(OTDId),
CONSTRAINT FK_OrderTranportDetail_OrderDetail_OrderId FOREIGN KEY(OrderId) REFERENCES OrderDetail(OrderId)
);