CREATE TABLE IF  NOT EXISTS PaymentDetail(
PDId VARCHAR(64),
OrderId INT NOT NULL,
BankName NVARCHAR(200),
TransactionId NVARCHAR(200),
AmountPaid FLOAT  DEFAULT 0,
TransactionDate DATETIME,
PDCrd DATETIME,
PDCrdBy NVARCHAR(200),
PDUpd	DATETIME,
PDUpdBy	NVARCHAR(200),
CONSTRAINT PK_PaymentDetail PRIMARY KEY(PDId),
CONSTRAINT FK_PaymentDetail_OrderDetail_OrderId FOREIGN KEY(OrderId) REFERENCES OrderDetail(OrderId)
);
